### ISSUE TITLE
Missing PIN

### ISSUE THREAD

**Issue by danimaro** [netmindz/balboa_GL_ML_spa_control#51]
Hello! This line refers to pin 18 which is never connected in esp32:
https://github.com/netmindz/balboa_GL_ML_spa_control/blob/fabc867b81be6bc6289bbb824b8cfb7d393e6c4f/sensor/src/sensor.ino#L420

 Am I missing something?

Regards,
Roz

**Comment by danimaro** [comment]
I fixed the bug and my esp32 is working now with mqtt broker and also as a webserver. Check the pull request! :-)

**Comment by netmindz** [comment]
Different boards expose different subsets of pins. You don't mention what board you are using

Glad you have a working setup
