### ISSUE TITLE
clearRXBuffer - not working as expcted

### ISSUE THREAD

**Issue by netmindz** [netmindz/balboa_GL_ML_spa_control#62]
Had to revert your commit for now @fherbert  - see https://github.com/netmindz/balboa_GL_ML_spa_control/pull/61

**Comment by fherbert** [comment]
I suspect its reading the FB messages that you are sending, I'll need to add support to just ignore this, it's not like we need to read the messages we send.

**Comment by fherbert** [comment]
Made a PR now which clears the RX buffer once we've sent a command, no point reading our own transmission!

**Comment by netmindz** [comment]
Thanks for the prompt response, I'll give that a try tomorrow

**Comment by netmindz** [comment]
Makes sense, I tested on the ESPHome code initially but that's not sending any commands yet
