### ISSUE TITLE
CalSpas 407T and CS6215R1A

### ISSUE THREAD

**Issue by smitterer** [netmindz/balboa_GL_ML_spa_control#76]
Hi!

I have a Cal Spa CS6215R1A which seems to be some special version of GS500Z with a Cal Spa 407T Display.

Here are some images:
https://photos.app.goo.gl/NoeShParJBgJhQFB9
https://photos.app.goo.gl/DKkjtgdfRPYoWXpB6

Not having a molex-connector but there are the solder joints available so those could be added.

Do you have an idea if your project would work with my controller?

Thanks!

**Comment by netmindz** [comment]
If you are right that is a GS500Z then it's more likely to colder to the https://github.com/MagnusPer/Balboa-GS510SZ
